services:
    db:
        image: postgres
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./scripts:/docker-entrypoint-initdb.d
        ports:
            - "5401:5432"
        env_file: "DFPostgres.env"

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
volumes:
    pgdata:

